/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Felix Yadomi (https://sketchfab.com/felixyadomi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boba-tea-2be1f3c8a0e54150bb61a438940b6921
Title: Boba Tea
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BubbleTea(props) {


  const { nodes, materials } = useGLTF('/boba_tea.glb')
  return (
    
    <group {...props} dispose={null}>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.boba}
        position={[-0.934, 1.337, -0.172]}
        rotation={[1.911, 0.032, 0.197]}
        scale={0.104}
      />


      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.stars}
        position={[-0.171, 3.832, 0.112]}
        rotation={[-0.662, 0.391, 2.065]}
        scale={0.202}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.stars}
        position={[-0.039, 3.52, 0.38]}
        rotation={[-0.338, 0.151, 1.725]}
        scale={0.138}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.stars}
        position={[-1.769, 3.746, -1.119]}
        rotation={[-1.555, 0.614, -2.811]}
        scale={0.255}
        
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.pastic_transparent}
        position={[0.108, 0.054, 0]}
        rotation={[0, 0, 0.381]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.pastic_transparent}
        position={[0.108, 0.054, 0]}
        rotation={[0, 0, 0.381]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.plastic_opaque}
        position={[0.182, -0.93, -0.271]}
        rotation={[0.066, 0.051, 0.313]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.material}
        position={[-0.269, 0.994, 0]}
        rotation={[0, 0, 0.381]}
        scale={1.082}
      />
      
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials['pastic_transparent.001']}
        position={[0.108, 0.054, 0]}
        rotation={[0, 0, 0.381]}
      />
      
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.material_0}
        position={[-0.66, 1.608, 0.029]}
        rotation={[0, 0, 0.381]}
        scale={0.689}
      />

    </group>
  )
}

useGLTF.preload('/boba_tea.glb')
