/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cosy_place.glb 
Author: smol_b0y (https://sketchfab.com/smol_b0y)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cosy-place-8de7f4aa1298433fad4bd97cb6e5e568
Title: Cosy Place
*/

//following a video: https://www.youtube.com/watch?v=f_ZxgQQ74Lc
//https://www.youtube.com/watch?v=pXpckHDDNYo&list=PLpepLKamtPjiUF6PvVUbIFhx9HaS0qJs_

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CosyPlace(props) {
  const { nodes, materials } = useGLTF('/cosy_place.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['0'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['1'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['2'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['3'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['4'].geometry} material={materials.CUp_Lid} position={[-0.002, -0.115, -0.003]} scale={1.008} />
      <mesh geometry={nodes['5'].geometry} material={materials.body_final_blinn} position={[-0.002, -0.098, -0.003]} scale={1.008} />
      <mesh geometry={nodes['6'].geometry} material={materials.CUp_Lid} position={[-0.002, -0.105, -0.003]} scale={1.008} />
      <mesh geometry={nodes['7'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['8'].geometry} material={materials.body_final_blinn} position={[-0.002, -0.114, -0.003]} scale={1.008} />
      <mesh geometry={nodes['9'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['10'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['11'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['12'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['13'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['14'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['15'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['16'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['17'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['18'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['19'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['20'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['21'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['22'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['23'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['24'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['25'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['26'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['27'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['28'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['29'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['30'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['31'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['32'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['33'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['34'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['35'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['36'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['37'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['38'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['39'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['40'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['41'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['42'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['43'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['44'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['45'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['46'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes['47'].geometry} material={materials.bobafinal} />
      <mesh geometry={nodes.polySurface287_tabletop1_0.geometry} material={materials.tabletop1} />
      <mesh geometry={nodes.polySurface288_tablecolour_0.geometry} material={materials.tablecolour} />
      <mesh geometry={nodes['48'].geometry} material={materials.shrooms} />
      <mesh geometry={nodes['49'].geometry} material={materials.shrooms} />
      <mesh geometry={nodes['50'].geometry} material={materials.shrooms} />
      <mesh geometry={nodes['51'].geometry} material={materials.treeee_leaaf} />
      <mesh geometry={nodes['52'].geometry} material={materials.treeee_leaaf} />
      <mesh geometry={nodes['53'].geometry} material={materials.treeee_leaaf} />
      <mesh geometry={nodes['54'].geometry} material={materials.shrooms} />
      <mesh geometry={nodes['55'].geometry} material={materials.shrooms} />
      <mesh geometry={nodes['56'].geometry} material={materials.shrooms} />
      <mesh geometry={nodes['57'].geometry} material={materials.shrooms} />
      <mesh geometry={nodes['58'].geometry} material={materials.treeee_leaaf} />
      <mesh geometry={nodes['59'].geometry} material={materials.treeee_leaaf} />
      <mesh geometry={nodes['60'].geometry} material={materials.treeee_leaaf} />
      <mesh geometry={nodes['61'].geometry} material={materials.shrooms} />
      <mesh geometry={nodes['62'].geometry} material={materials.shrooms} />
      <mesh geometry={nodes['63'].geometry} material={materials.tablecolour} />
      <mesh geometry={nodes['64'].geometry} material={materials.tablecolour} />
      <mesh geometry={nodes['65'].geometry} material={materials.tabletop1} />
      <mesh geometry={nodes['66'].geometry} material={materials.tablecolour} />
      <mesh geometry={nodes['67'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['68'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['69'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['70'].geometry} material={materials.aiAmbientOcclusion1} />
      <mesh geometry={nodes['71'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['72'].geometry} material={materials.switch_blue} />
      <mesh geometry={nodes['73'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['74'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['75'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['76'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['77'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['78'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['79'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['80'].geometry} material={materials.switch_green} />
      <mesh geometry={nodes['81'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['82'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['83'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['84'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['85'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes['86'].geometry} material={materials.switch2} />
      <mesh geometry={nodes['87'].geometry} material={materials.lambert8} />
      <mesh geometry={nodes.pSphere15_sky_dome_0.geometry} material={materials.sky_dome} scale={55.578} />
    </group>
  )
}

useGLTF.preload('/cosy_place.glb')
